# Generated by Django 4.2.5 on 2023-12-27 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompañiaPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Desarrolladores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_salida', models.DateField(null=True, verbose_name='Fecha de salida')),
                ('total_videojuegos', models.PositiveIntegerField()),
                ('precio_original', models.FloatField()),
                ('picture_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('compañia_plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.compañiaplataforma')),
            ],
        ),
        migrations.CreateModel(
            name='VideoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField(null=True, verbose_name='Fecha de Lanzamiento')),
                ('descripcion', models.TextField()),
                ('temas', models.CharField(max_length=100)),
                ('picture_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('desarrolladores', models.ManyToManyField(to='principal.desarrolladores')),
                ('genero', models.ManyToManyField(to='principal.genero')),
                ('plataformas', models.ManyToManyField(to='principal.plataforma')),
            ],
        ),
    ]
