# Generated by Django 4.2.5 on 2023-12-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
