# Generated by Django 4.2.5 on 2023-12-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_videojuego_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='total_videojuegos',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
