# Generated by Django 4.2.5 on 2023-12-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_plataforma_total_videojuegos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='precio_original',
            field=models.FloatField(null=True),
        ),
    ]
